const box = () => import('../components/box')
const oil = () => import('../components/home/oil')
const used = () => import('../components/home/used')
const meat = () => import('../components/home/meat')
const home = () => import('../components/home/home')
const deli = () => import('../components/home/deli')
const dairy = () => import('../components/home/dairy')
const frult = () => import('../components/home/frult')
const water = () => import('../components/home/water')
const drinks = () => import('../components/home/drinks')
const snacks = () => import('../components/home/snacks')
const kitchen = () => import('../components/home/kitchen')
const nourishing = () => import('../components/home/nourishing')
const vegetables = () => import('../components/home/vegetables')
const sort = () => import('../components/sort/sort')
const sort1 = () => import('../components/sort/sort1')
const sanji = () => import('../components/sort/sanji')
const mybl = () => import('../components/mybl')
const eat = () => import('../components/eat')
const shopcar = () => import('../components/shopcar')
const register = () => import('../components/register')
const login = () => import('../components/login')
const customer = () => import('../components/customer/customer')
const search = () => import('../components/sort/search')
const admin = () => import('../components/admin/admin')
const benlaiweb = () => import('../webviews/index.vue')
export {
    box,oil,used,meat,home,deli,dairy,frult,water,drinks,snacks,kitchen,nourishing,vegetables,sort,sort1,sanji,mybl,eat,shopcar,
    register,login,customer,search,admin,benlaiweb
}